### ISSUE TITLE
Validate version 0.0.3 and its documentation

### ISSUE THREAD

**Issue by amotl** [hiveeyes/ds18b20-datalogger#10]
## Call for Support
After recent refactorings and the release of version 0.0.3, it would be so sweet to receive support validating the implementation and the corresponding documentation thoroughly. Can we humbly ask you to exercise it on behalf of your hardware before installing it on the hive, @bee-mois?

## Resources
- [README](https://github.com/hiveeyes/ds18b20-datalogger/blob/main/README.md)
- [Development Sandbox](https://github.com/hiveeyes/ds18b20-datalogger/blob/main/docs/sandbox.md)
- [Production Setup](https://github.com/hiveeyes/ds18b20-datalogger/blob/main/docs/production.md)

## Related
- GH-9

**Comment by bee-mois** [comment]
tested README --> Development Sandbox and it works.
there is an [issue](https://github.com/hiveeyes/ds18b20-datalogger/issues/11) with a fixed uid in dashboard template json. it is not interfering with installation but it has the potential to break existing desktops of others.

**Comment by amotl** [comment]
Thank you for testing, and for creating GH-11. Let's close this issue, as I think it does not have any more actionable items inside. If you think differently, please re-open.
