### ISSUE TITLE
temperature offset for particular sensor?

### ISSUE THREAD

**Issue by bee-mois** [hiveeyes/ds18b20-datalogger#12]
some sensors show obvious offsets:
![image](https://github.com/hiveeyes/ds18b20-datalogger/assets/26469299/70b89fe1-b0f6-4b7c-b750-f526c87a95cf)

in older code revisions ([this](https://github.com/hiveeyes/ds18b20-datalogger/blob/db59c8aebd77530cac68d0e7cebe8464ce42c437/ds18b20_datalogger/core.py) and older) i had the possibility to add values to correct those offsets, for example:
```
        if folder == "/sys/bus/w1/devices/28-0346d4430b06":
            label = "temp-ir-1-1"
            temp_ir_1_1 = tc + 0.5
```
tc + 0.5 is correcting a negative 0.5°C offset of the given sensor.

where would i set offsets like that in the actual code, where the sensor config takes place in .yaml?

**Comment by amotl** [comment]
Thanks. Improved with e4b0b6915a on behalf of GH-14.

**Comment by bee-mois** [comment]
thank you very many.
