### ISSUE TITLE
UX: Improve configuration and first-use

### ISSUE THREAD

**Issue by amotl** [hiveeyes/ds18b20-datalogger#13]
> Don't forget to fill with your own mqtt connection info and with your sensor ids/device addresses, and it works like a charm.

_Originally posted by @bee-mois in https://github.com/hiveeyes/ds18b20-datalogger/issues/9#issuecomment-2068132535_

**Comment by amotl** [comment]
Thanks for your suggestion. Do you think we should improve the situation for first-time users? For example, the `make-config` scaffolder could emit an invalid configuration file, or inject some attribute that will get recognized that the user did not make any changes to the file, and then, the program will respond appropriately, and raise a relevant admonition to the user that they should adjust the configuration file first, before invoking the data logger. wdyt?

**Comment by bee-mois** [comment]
> some attribute that will get recognized that the user did not make any changes to the file

one of the example sensor ids should be good. not very likely that one of them is already correct for a first-time user.
and the placeholders in the mqtt section: same same.
two different warnings should possibly result: 
"Are you shure you privided your specific sensor device path information in datalogger.yml?"
and/or
"You did not  set up your MQTT credentials in datalogger.yml."

**Comment by amotl** [comment]
We can not use yours if we really want to discriminate between both sections. Otherwise, the logger will not work on your end, but croak instead. I think it will be good enough to have a one-time catch-all warning about the need to edit the configuration before running the program.

Thinking about it once more, I think we can get around any complexities and configuration file markers, by just emitting a corresponding message to STDERR, when invoking the `make-config` subcommand.

**Comment by bee-mois** [comment]
> by just emitting a corresponding message to STDERR, when invoking the `make-config` subcommand

yeah, lets keep it simple and still remind people of stuff at the right spot in the right moment. i like that.

**Comment by amotl** [comment]
Thanks. Improved with 555248eccb on behalf of GH-14.
