### ISSUE TITLE
missing directory /etc/ds18b20-datalogger in installation for production

### ISSUE THREAD

**Issue by bee-mois** [hiveeyes/ds18b20-datalogger#15]
do we have to deal with this one?

`~# /opt/ds18b20-datalogger/bin/ds18b20-datalogger make-config > /etc/ds18b20-datalogger/config.yaml` :x: `-bash: /etc/ds18b20-datalogger/config.yaml: No such file or directory`

**Comment by amotl** [comment]
Isn't it [fixed already](https://community.hiveeyes.org/t/ds18b20-datenlogger-mit-raspberry-pi-und-grafana/5321/13) in the documentation, on behalf of 70742b73520? Or is it a different error?

**Comment by bee-mois** [comment]
my blindness, sorry, closing this as quick as i opened it.
