### ISSUE TITLE
New configuration file using YAML

### ISSUE THREAD

**Issue by amotl** [hiveeyes/ds18b20-datalogger#9]
## Introduction

The new configuration file for this program is using the [YAML](https://en.wikipedia.org/wiki/YAML) format.

![image](https://github.com/hiveeyes/ds18b20-datalogger/assets/453543/a8972a33-b387-4e7d-a3fa-ef005232f65c)
-- https://www.reddit.com/r/ProgrammerHumor/comments/qz0av8/box_of_devops/

## Synopsis
Use the `read` or `run` subcommands together with a configuration file to invoke a measurement reading.
```shell
ds18b20-datalogger read /path/to/datalogger.yaml
```
```shell
ds18b20-datalogger run /path/to/datalogger.yaml
```

## Configuration File
After installing the program, you can easily create a configuration file blueprint, using the `make-config` subcommand.
```shell
ds18b20-datalogger make-config > datalogger.yaml
```
Other than this, see also [etc/mois.yaml] as a full working example, defining a 5x6 temperature sensor matrix, supporting beehive monitoring.

[etc/mois.yaml]: https://github.com/hiveeyes/ds18b20-datalogger/blob/main/etc/mois.yaml

**Comment by bee-mois** [comment]
dont forget to fill with your own mqtt connection info and with your sensor ids/device addresses, and it works like a charm.
